### PR TITLE
Fix URL display style

### LINKED ISSUE #13: File url not showing up
Sometimes the file url may not show up.  The extent or cause of this issue is unknown.

You are still able to open the file directory of the pdf and open the pdf.

Scr:
image

#### edit:

- the displayed url must be displayed on a single line
- url should be as readable as possible

### After debugging a little, it looks like the issue happens when the filename is too long which pushes the url (located below the title) out of the div, and out of sight.

### PR DESCRIPTION
**Pull request by marcosnils**
- Removes unnecessary function
- Fixes #13

### CODE REVIEW

**Comment by marcosnils** [comment]
image

This is how it looks in my machine. The problem was that several filenames didn't have the `\\` at all in the path so that line was causing the url not to render at all. 

What you can do if you don't want the path to mess with the length is truncate the url with ellipsis using css (https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/)

**Comment by marcosnils** [comment]
> Also - all the file paths begin with "file://" if I can recall correctly. So the issue is something else. See the updates issue #13.

That wasn't my case. The issue about url's not appearing was because a styling issue that I also fixed in the PR. The URL's are there, it's just that the CSS styles were causing the file name to overlap them. You can try merging this PR locally in your machine and check out how it works.

**Comment by alexweininger** [comment]
Will do👍

**Comment by alexweininger** [comment]
@marcosnils just checked it out, looks great! Sorry for my pestering.

I will note that there are further improvements from this that need to be made.  I will link the issues here later.

**Comment by marcosnils** [comment]
> @marcosnils just checked it out, looks great! Sorry for my pestering.

No worries, glad to help! :)

**Pull request merged**
